### ISSUE TITLE
Proxy connection has been detected

### ISSUE THREAD

**Issue by TheTabKey** [nitin30kumar/edu-mail--auto-generator#2]
First I did have to enable cookies for it to to show anything. Second is this proxy connection has been detected.
https://i.imgur.com/9VTipWG.png

**Comment by nitinkumar30** [comment]
> First I did have to enable cookies for it to to show anything. Second is this proxy connection has been detected. https://i.imgur.com/9VTipWG.png

Hi @TheTabKey, the first one is expected. You must have to enable cookies for obvious reasons.
Secondly, it's clearly obvious that college doesn't want to have a connection with outsider proxies like Tor. This comes under security incidents. Hope I'm clear to you. 

Kindly close this issue if I'm clear to you.
